version: '3.3'

services:

  n8n:
    image: n8nio/n8n:latest
    restart: ${N8N_RESTART}
    container_name: n8n
    hostname: n8n.local
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
    ports:
      - '127.0.0.1:${N8N_PORT}:5678'
    volumes:
      - ./data/n8n:/home/node/.n8n
    links:
      - mysql:database
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: ${MYSQL_RESTART}
    container_name: mysql
    hostname: mysql.local
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    ports:
      - '127.0.0.1:${MYSQL_PORT}:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  memos:
    image: neosmemo/memos:latest
    restart: ${MEMOS_RESTART}
    container_name: memos
    hostname: memos.local
    volumes:
      - ./data/memos:/var/opt/memos
    ports:
      - '127.0.0.1:${MEMOS_PORT}:5230'

  httpd:
    image: httpd:latest
    restart: ${HTTPD_RESTART}
    container_name: httpd
    hostname: httpd.local
    ports:
      - '127.0.0.1:${HTTPD_PORT}:80'
    volumes:
      - ./data/httpd:/usr/local/apache2/htdocs

  kuma:
    image: louislam/uptime-kuma:latest
    restart: ${KUMA_RESTART}
    container_name: kuma
    hostname: kuma.local
    ports:
      - '127.0.0.1:${KUMA_PORT}:3001'
    volumes:
      - ./data/kuma:/app/data

  portainer:
    image: portainer/portainer-ce:latest
    restart: ${PORTAINER_RESTART}
    container_name: portainer
    hostname: portainer.local
    ports:
      - '127.0.0.1:${PORTAINER_PORT}:9443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
