version: '3.9'
services:
  apache:
    image: httpd:latest
    container_name: apache-static
    ports:
      - '127.0.0.1:2997:80'
    volumes:
      - ./public/:/usr/local/apache2/htdocs
    restart: always
